spring:
  reactor:
    context-propagation: auto

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://sgivu-discovery:8761/eureka}

config:
  base-url:
    endpoint:
      sgivu-auth: ${SGIVU_AUTH_URL:http://sgivu-auth:9000}

server:
  port: ${PORT:8080}

client:
  angular-client:
    url: ${ANGULAR_APP_URL:http://localhost:4200}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://sgivu-zipkin:9411/api/v2/spans

logging:
  level:
    root: INFO
