spring:
  datasource:
    url: jdbc:postgresql://${PROD_AUTH_DB_HOST:host.docker.internal}:${PROD_AUTH_DB_PORT:5432}/${PROD_AUTH_DB_NAME}
    username: ${PROD_AUTH_DB_USERNAME}
    password: ${PROD_AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: true
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
  session:
    timeout: 2h

angular-client:
  url: ${PROD_ANGULAR_APP_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

openapi:
  server:
    url: ${OPENAPI_SERVER_URL}
