spring:
  datasource:
    url: jdbc:postgresql://${PROD_CLIENT_DB_HOST}:${PROD_CLIENT_DB_PORT}/${PROD_CLIENT_DB_NAME}
    username: ${PROD_CLIENT_DB_USERNAME}
    password: ${PROD_CLIENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: true
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

openapi:
  server:
    url: ${OPENAPI_SERVER_URL}
